-- 02/06/2017 - GERCY CAMPOS
-- CRIAÇÃO DE TABELAS PARA ALTERAÇÃO DA ENGINE DE RELATÓRIOS.
-- REFERENCIAS: HTTPS://WWW.DEVEXPRESS.COM/SUPPORT/CENTER/EXAMPLE/DETAILS/E4657
 
CREATE TABLE DBO.ITS_SQL_QUERIES (
  IdQuery VARCHAR(38) NOT NULL DEFAULT (NEWID())
 ,CodigoQuery VARCHAR(10) NOT NULL
 ,NomeQuery VARCHAR(50) NULL
 ,CorpoQuery VARCHAR(8000) NOT NULL
 ,DataCriacao DATETIME NOT NULL
 ,DataAlteracao DATETIME NULL
  CONSTRAINT PK_ITS_SQL_QUERIES_IDQUERY PRIMARY KEY CLUSTERED (IdQuery)
) ON [PRIMARY]
GO

CREATE TABLE DBO.ITS_REPORT_DATASOURCE (
  IdDatasource VARCHAR(38) NOT NULL DEFAULT (NEWID())
 ,IdReport INT NOT NULL
 ,IdQuery VARCHAR(38) NOT NULL
 ,DataMember BIT NULL
  CONSTRAINT PK_ITS_REPORT_DATASOURCE_IDDATASOURCE PRIMARY KEY CLUSTERED (IdDataSource)
) ON [PRIMARY]
GO

ALTER TABLE DBO.ITS_REPORT_DATASOURCE WITH NOCHECK
ADD CONSTRAINT FK_ITS_REPORT_DATASOURCE_IDQUERY FOREIGN KEY (IDQUERY) REFERENCES DBO.ITS_SQL_QUERIES (IdQuery)
GO

ALTER TABLE DBO.ITS_REPORT_DATASOURCE WITH NOCHECK
ADD CONSTRAINT FK_ITS_REPORT_DATASOURCE_IDREPORT FOREIGN KEY (IDREPORT) REFERENCES DBO.ITS_REPORT_IMAGE (IdReport)
GO
