CREATE TABLE Pais (
  IdPais INT IDENTITY
 ,CodigoSiscomex VARCHAR(3) NOT NULL
 ,NomePais VARCHAR(38) NOT NULL
 ,CONSTRAINT PK_Pais_IdPais PRIMARY KEY CLUSTERED (IdPais)
) ON [PRIMARY]
GO

CREATE INDEX IDX_Pais_CodigoSiscomex
ON Pais (CodigoSiscomex)
ON [PRIMARY]
GO

CREATE INDEX IDX_Pais_NomePais
ON Pais (NomePais)
ON [PRIMARY]
GO

insert into Pais (CodigoSiscomex, NomePais) values ('1','CANADA');
insert into Pais (CodigoSiscomex, NomePais) values ('2','JAMAICA');
insert into Pais (CodigoSiscomex, NomePais) values ('13','AFEGANISTAO');
insert into Pais (CodigoSiscomex, NomePais) values ('17','ALBANIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('23','ALEMANHA');
insert into Pais (CodigoSiscomex, NomePais) values ('31','BURKINA FASO');
insert into Pais (CodigoSiscomex, NomePais) values ('37','ANDORRA');
insert into Pais (CodigoSiscomex, NomePais) values ('40','ANGOLA');
insert into Pais (CodigoSiscomex, NomePais) values ('41','ANGUILLA');
insert into Pais (CodigoSiscomex, NomePais) values ('43','ANTIGUA E BARBUDA');
insert into Pais (CodigoSiscomex, NomePais) values ('47','ANTILHAS HOLANDESAS');
insert into Pais (CodigoSiscomex, NomePais) values ('53','ARABIA SAUDITA');
insert into Pais (CodigoSiscomex, NomePais) values ('59','ARGELIA');
insert into Pais (CodigoSiscomex, NomePais) values ('63','ARGENTINA');
insert into Pais (CodigoSiscomex, NomePais) values ('64','ARMENIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('65','ARUBA');
insert into Pais (CodigoSiscomex, NomePais) values ('69','AUSTRALIA');
insert into Pais (CodigoSiscomex, NomePais) values ('72','AUSTRIA');
insert into Pais (CodigoSiscomex, NomePais) values ('73','AZERBAIJAO, REPUBLICA DO');
insert into Pais (CodigoSiscomex, NomePais) values ('77','BAHAMAS, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('80','BAHREIN, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('81','BANGLADESH');
insert into Pais (CodigoSiscomex, NomePais) values ('83','BARBADOS');
insert into Pais (CodigoSiscomex, NomePais) values ('85','BELARUS, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('87','BELGICA');
insert into Pais (CodigoSiscomex, NomePais) values ('88','BELIZE');
insert into Pais (CodigoSiscomex, NomePais) values ('90','BERMUDAS');
insert into Pais (CodigoSiscomex, NomePais) values ('93','MIANMAR (BIRMANIA)');
insert into Pais (CodigoSiscomex, NomePais) values ('97','BOLIVIA');
insert into Pais (CodigoSiscomex, NomePais) values ('98','BOSNIA-HERZEGOVINA (REPUBLICA DA)');
insert into Pais (CodigoSiscomex, NomePais) values ('101','BOTSUANA');
insert into Pais (CodigoSiscomex, NomePais) values ('105','BRASIL');
insert into Pais (CodigoSiscomex, NomePais) values ('108','BRUNEI');
insert into Pais (CodigoSiscomex, NomePais) values ('111','BULGARIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('115','BURUNDI');
insert into Pais (CodigoSiscomex, NomePais) values ('119','BUTAO');
insert into Pais (CodigoSiscomex, NomePais) values ('127','CABO VERDE, REPUBLICA DE');
insert into Pais (CodigoSiscomex, NomePais) values ('137','CAYMAN, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('141','CAMBOJA');
insert into Pais (CodigoSiscomex, NomePais) values ('145','CAMAROES');
insert into Pais (CodigoSiscomex, NomePais) values ('149','CANADA');
insert into Pais (CodigoSiscomex, NomePais) values ('150','ILHAS DO CANAL');
insert into Pais (CodigoSiscomex, NomePais) values ('151','CANARIAS, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('153','CAZAQUISTAO, REPUBLICA DO');
insert into Pais (CodigoSiscomex, NomePais) values ('154','CATAR');
insert into Pais (CodigoSiscomex, NomePais) values ('158','CHILE');
insert into Pais (CodigoSiscomex, NomePais) values ('160','CHINA, REPUBLICA POPULAR');
insert into Pais (CodigoSiscomex, NomePais) values ('161','FORMOSA (TAIWAN)');
insert into Pais (CodigoSiscomex, NomePais) values ('163','CHIPRE');
insert into Pais (CodigoSiscomex, NomePais) values ('165','COCOS(KEELING),ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('169','COLOMBIA');
insert into Pais (CodigoSiscomex, NomePais) values ('173','COMORES, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('177','CONGO');
insert into Pais (CodigoSiscomex, NomePais) values ('183','COOK, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('187','COREIA, REP.POP.DEMOCRATICA');
insert into Pais (CodigoSiscomex, NomePais) values ('190','COREIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('193','COSTA DO MARFIM');
insert into Pais (CodigoSiscomex, NomePais) values ('195','CROACIA (REPUBLICA DA)');
insert into Pais (CodigoSiscomex, NomePais) values ('196','COSTA RICA');
insert into Pais (CodigoSiscomex, NomePais) values ('198','COVEITE');
insert into Pais (CodigoSiscomex, NomePais) values ('199','CUBA');
insert into Pais (CodigoSiscomex, NomePais) values ('200','Curaçao');
insert into Pais (CodigoSiscomex, NomePais) values ('229','BENIN');
insert into Pais (CodigoSiscomex, NomePais) values ('232','DINAMARCA');
insert into Pais (CodigoSiscomex, NomePais) values ('235','DOMINICA,ILHA');
insert into Pais (CodigoSiscomex, NomePais) values ('237','Dubai');
insert into Pais (CodigoSiscomex, NomePais) values ('239','EQUADOR');
insert into Pais (CodigoSiscomex, NomePais) values ('240','EGITO');
insert into Pais (CodigoSiscomex, NomePais) values ('243','Eritreia');
insert into Pais (CodigoSiscomex, NomePais) values ('244','EMIRADOS ARABES UNIDOS');
insert into Pais (CodigoSiscomex, NomePais) values ('245','ESPANHA');
insert into Pais (CodigoSiscomex, NomePais) values ('246','ESLOVENIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('247','ESLOVACA, REPUBLICA');
insert into Pais (CodigoSiscomex, NomePais) values ('249','ESTADOS UNIDOS');
insert into Pais (CodigoSiscomex, NomePais) values ('251','ESTONIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('253','ETIOPIA');
insert into Pais (CodigoSiscomex, NomePais) values ('255','FALKLAND (ILHAS MALVINAS)');
insert into Pais (CodigoSiscomex, NomePais) values ('259','FEROE, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('263','Fezzan');
insert into Pais (CodigoSiscomex, NomePais) values ('267','FILIPINAS');
insert into Pais (CodigoSiscomex, NomePais) values ('271','FINLANDIA');
insert into Pais (CodigoSiscomex, NomePais) values ('275','FRANCA');
insert into Pais (CodigoSiscomex, NomePais) values ('281','GABAO');
insert into Pais (CodigoSiscomex, NomePais) values ('285','GAMBIA');
insert into Pais (CodigoSiscomex, NomePais) values ('289','GANA');
insert into Pais (CodigoSiscomex, NomePais) values ('291','GEORGIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('293','GIBRALTAR');
insert into Pais (CodigoSiscomex, NomePais) values ('297','GRANADA');
insert into Pais (CodigoSiscomex, NomePais) values ('301','GRECIA');
insert into Pais (CodigoSiscomex, NomePais) values ('305','GROENLANDIA');
insert into Pais (CodigoSiscomex, NomePais) values ('309','GUADALUPE');
insert into Pais (CodigoSiscomex, NomePais) values ('313','GUAM');
insert into Pais (CodigoSiscomex, NomePais) values ('317','GUATEMALA');
insert into Pais (CodigoSiscomex, NomePais) values ('325','GUIANA FRANCESA');
insert into Pais (CodigoSiscomex, NomePais) values ('329','GUINE');
insert into Pais (CodigoSiscomex, NomePais) values ('331','GUINE-EQUATORIAL');
insert into Pais (CodigoSiscomex, NomePais) values ('334','GUINE-BISSAU');
insert into Pais (CodigoSiscomex, NomePais) values ('337','GUIANA');
insert into Pais (CodigoSiscomex, NomePais) values ('341','HAITI');
insert into Pais (CodigoSiscomex, NomePais) values ('345','HONDURAS');
insert into Pais (CodigoSiscomex, NomePais) values ('351','HONG KONG');
insert into Pais (CodigoSiscomex, NomePais) values ('355','HUNGRIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('357','IEMEN');
insert into Pais (CodigoSiscomex, NomePais) values ('359','MAN, ILHA DE');
insert into Pais (CodigoSiscomex, NomePais) values ('361','INDIA');
insert into Pais (CodigoSiscomex, NomePais) values ('365','INDONESIA');
insert into Pais (CodigoSiscomex, NomePais) values ('367','Inglaterra');
insert into Pais (CodigoSiscomex, NomePais) values ('369','IRAQUE');
insert into Pais (CodigoSiscomex, NomePais) values ('372','IRA, REPUBLICA ISLAMICA DO');
insert into Pais (CodigoSiscomex, NomePais) values ('375','IRLANDA');
insert into Pais (CodigoSiscomex, NomePais) values ('379','ISLANDIA');
insert into Pais (CodigoSiscomex, NomePais) values ('383','ISRAEL');
insert into Pais (CodigoSiscomex, NomePais) values ('386','ITALIA');
insert into Pais (CodigoSiscomex, NomePais) values ('388','IUGOSLAVIA, REP.FED.DA');
insert into Pais (CodigoSiscomex, NomePais) values ('391','JAMAICA');
insert into Pais (CodigoSiscomex, NomePais) values ('396','JOHNSTON, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('399','JAPAO');
insert into Pais (CodigoSiscomex, NomePais) values ('403','JORDANIA');
insert into Pais (CodigoSiscomex, NomePais) values ('411','KIRIBATI');
insert into Pais (CodigoSiscomex, NomePais) values ('420','LAOS, REP.POP.DEMOCR.DO');
insert into Pais (CodigoSiscomex, NomePais) values ('423','LEBUAN,ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('426','LESOTO');
insert into Pais (CodigoSiscomex, NomePais) values ('427','LETONIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('431','LIBANO');
insert into Pais (CodigoSiscomex, NomePais) values ('434','LIBERIA');
insert into Pais (CodigoSiscomex, NomePais) values ('438','LIBIA');
insert into Pais (CodigoSiscomex, NomePais) values ('440','LIECHTENSTEIN');
insert into Pais (CodigoSiscomex, NomePais) values ('442','LITUANIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('445','LUXEMBURGO');
insert into Pais (CodigoSiscomex, NomePais) values ('447','MACAU');
insert into Pais (CodigoSiscomex, NomePais) values ('449','MACEDONIA, ANT.REP.IUGOSLAVA');
insert into Pais (CodigoSiscomex, NomePais) values ('450','MADAGASCAR');
insert into Pais (CodigoSiscomex, NomePais) values ('452','ILHA DA MADEIRA');
insert into Pais (CodigoSiscomex, NomePais) values ('455','MALASIA');
insert into Pais (CodigoSiscomex, NomePais) values ('458','MALAVI');
insert into Pais (CodigoSiscomex, NomePais) values ('461','MALDIVAS');
insert into Pais (CodigoSiscomex, NomePais) values ('464','MALI');
insert into Pais (CodigoSiscomex, NomePais) values ('467','MALTA');
insert into Pais (CodigoSiscomex, NomePais) values ('472','MARIANAS DO NORTE');
insert into Pais (CodigoSiscomex, NomePais) values ('474','MARROCOS');
insert into Pais (CodigoSiscomex, NomePais) values ('476','MARSHALL,ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('477','MARTINICA');
insert into Pais (CodigoSiscomex, NomePais) values ('485','MAURICIO');
insert into Pais (CodigoSiscomex, NomePais) values ('488','MAURITANIA');
insert into Pais (CodigoSiscomex, NomePais) values ('490','MIDWAY, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('493','MEXICO');
insert into Pais (CodigoSiscomex, NomePais) values ('494','MOLDAVIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('495','MONACO');
insert into Pais (CodigoSiscomex, NomePais) values ('497','MONGOLIA');
insert into Pais (CodigoSiscomex, NomePais) values ('498','MONTENEGRO');
insert into Pais (CodigoSiscomex, NomePais) values ('499','MICRONESIA');
insert into Pais (CodigoSiscomex, NomePais) values ('501','MONTSERRAT,ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('505','MOCAMBIQUE');
insert into Pais (CodigoSiscomex, NomePais) values ('507','NAMIBIA');
insert into Pais (CodigoSiscomex, NomePais) values ('508','NAURU');
insert into Pais (CodigoSiscomex, NomePais) values ('511','CHRISTMAS,ILHA (NAVIDAD)');
insert into Pais (CodigoSiscomex, NomePais) values ('517','NEPAL');
insert into Pais (CodigoSiscomex, NomePais) values ('521','NICARAGUA');
insert into Pais (CodigoSiscomex, NomePais) values ('525','NIGER');
insert into Pais (CodigoSiscomex, NomePais) values ('528','NIGERIA');
insert into Pais (CodigoSiscomex, NomePais) values ('531','NIUE,ILHA');
insert into Pais (CodigoSiscomex, NomePais) values ('535','NORFOLK,ILHA');
insert into Pais (CodigoSiscomex, NomePais) values ('538','NORUEGA');
insert into Pais (CodigoSiscomex, NomePais) values ('542','NOVA CALEDONIA');
insert into Pais (CodigoSiscomex, NomePais) values ('545','PAPUA NOVA GUINE');
insert into Pais (CodigoSiscomex, NomePais) values ('548','NOVA ZELANDIA');
insert into Pais (CodigoSiscomex, NomePais) values ('551','VANUATU');
insert into Pais (CodigoSiscomex, NomePais) values ('556','OMA');
insert into Pais (CodigoSiscomex, NomePais) values ('563','Pacífico, Ilhas do (administ. dos EUA)');
insert into Pais (CodigoSiscomex, NomePais) values ('566','PACIFICO,ILHAS DO (POSSESSAO DOS EUA)');
insert into Pais (CodigoSiscomex, NomePais) values ('573','PAISES BAIXOS (HOLANDA)');
insert into Pais (CodigoSiscomex, NomePais) values ('575','PALAU');
insert into Pais (CodigoSiscomex, NomePais) values ('576','PAQUISTAO');
insert into Pais (CodigoSiscomex, NomePais) values ('578','PALESTINA');
insert into Pais (CodigoSiscomex, NomePais) values ('580','PANAMA');
insert into Pais (CodigoSiscomex, NomePais) values ('586','PARAGUAI');
insert into Pais (CodigoSiscomex, NomePais) values ('589','PERU');
insert into Pais (CodigoSiscomex, NomePais) values ('593','PITCAIRN,ILHA');
insert into Pais (CodigoSiscomex, NomePais) values ('599','POLINESIA FRANCESA');
insert into Pais (CodigoSiscomex, NomePais) values ('603','POLONIA, REPUBLICA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('607','PORTUGAL');
insert into Pais (CodigoSiscomex, NomePais) values ('611','PORTO RICO');
insert into Pais (CodigoSiscomex, NomePais) values ('623','QUENIA');
insert into Pais (CodigoSiscomex, NomePais) values ('625','QUIRGUIZ, REPUBLICA');
insert into Pais (CodigoSiscomex, NomePais) values ('628','REINO UNIDO');
insert into Pais (CodigoSiscomex, NomePais) values ('640','REPUBLICA CENTRO-AFRICANA');
insert into Pais (CodigoSiscomex, NomePais) values ('647','REPUBLICA DOMINICANA');
insert into Pais (CodigoSiscomex, NomePais) values ('660','REUNIAO, ILHA');
insert into Pais (CodigoSiscomex, NomePais) values ('665','ZIMBABUE');
insert into Pais (CodigoSiscomex, NomePais) values ('670','ROMENIA');
insert into Pais (CodigoSiscomex, NomePais) values ('675','RUANDA');
insert into Pais (CodigoSiscomex, NomePais) values ('676','RUSSIA, FEDERACAO DA');
insert into Pais (CodigoSiscomex, NomePais) values ('677','SALOMAO, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('678','SAINT KITTS E NEVIS');
insert into Pais (CodigoSiscomex, NomePais) values ('685','SAARA OCIDENTAL');
insert into Pais (CodigoSiscomex, NomePais) values ('687','EL SALVADOR');
insert into Pais (CodigoSiscomex, NomePais) values ('690','SAMOA');
insert into Pais (CodigoSiscomex, NomePais) values ('691','SAMOA AMERICANA');
insert into Pais (CodigoSiscomex, NomePais) values ('695','SAO CRISTOVAO E NEVES,ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('697','SAN MARINO');
insert into Pais (CodigoSiscomex, NomePais) values ('700','SAO PEDRO E MIQUELON');
insert into Pais (CodigoSiscomex, NomePais) values ('705','SAO VICENTE E GRANADINAS');
insert into Pais (CodigoSiscomex, NomePais) values ('710','SANTA HELENA');
insert into Pais (CodigoSiscomex, NomePais) values ('715','SANTA LUCIA');
insert into Pais (CodigoSiscomex, NomePais) values ('720','SAO TOME E PRINCIPE, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('728','SENEGAL');
insert into Pais (CodigoSiscomex, NomePais) values ('731','SEYCHELLES');
insert into Pais (CodigoSiscomex, NomePais) values ('735','SERRA LEOA');
insert into Pais (CodigoSiscomex, NomePais) values ('737','Servia');
insert into Pais (CodigoSiscomex, NomePais) values ('741','CINGAPURA');
insert into Pais (CodigoSiscomex, NomePais) values ('744','SIRIA, REPUBLICA ARABE DA');
insert into Pais (CodigoSiscomex, NomePais) values ('748','SOMALIA');
insert into Pais (CodigoSiscomex, NomePais) values ('750','SRI LANKA');
insert into Pais (CodigoSiscomex, NomePais) values ('754','SUAZILANDIA');
insert into Pais (CodigoSiscomex, NomePais) values ('756','AFRICA DO SUL');
insert into Pais (CodigoSiscomex, NomePais) values ('759','SUDAO');
insert into Pais (CodigoSiscomex, NomePais) values ('760','SUDAO DO SUL');
insert into Pais (CodigoSiscomex, NomePais) values ('764','SUECIA');
insert into Pais (CodigoSiscomex, NomePais) values ('767','SUICA');
insert into Pais (CodigoSiscomex, NomePais) values ('770','SURINAME');
insert into Pais (CodigoSiscomex, NomePais) values ('772','TADJIQUISTAO, REPUBLICA DO');
insert into Pais (CodigoSiscomex, NomePais) values ('776','TAILANDIA');
insert into Pais (CodigoSiscomex, NomePais) values ('780','TANZANIA, REP.UNIDA DA');
insert into Pais (CodigoSiscomex, NomePais) values ('782','TERRITORIO BRIT.OC.INDICO');
insert into Pais (CodigoSiscomex, NomePais) values ('783','DJIBUTI');
insert into Pais (CodigoSiscomex, NomePais) values ('788','CHADE');
insert into Pais (CodigoSiscomex, NomePais) values ('791','TCHECA, REPUBLICA');
insert into Pais (CodigoSiscomex, NomePais) values ('795','TIMOR LESTE');
insert into Pais (CodigoSiscomex, NomePais) values ('800','TOGO');
insert into Pais (CodigoSiscomex, NomePais) values ('805','TOQUELAU,ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('810','TONGA');
insert into Pais (CodigoSiscomex, NomePais) values ('815','TRINIDAD E TOBAGO');
insert into Pais (CodigoSiscomex, NomePais) values ('820','TUNISIA');
insert into Pais (CodigoSiscomex, NomePais) values ('823','TURCAS E CAICOS,ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('824','TURCOMENISTAO, REPUBLICA DO');
insert into Pais (CodigoSiscomex, NomePais) values ('827','TURQUIA');
insert into Pais (CodigoSiscomex, NomePais) values ('828','TUVALU');
insert into Pais (CodigoSiscomex, NomePais) values ('831','UCRANIA');
insert into Pais (CodigoSiscomex, NomePais) values ('833','UGANDA');
insert into Pais (CodigoSiscomex, NomePais) values ('845','URUGUAI');
insert into Pais (CodigoSiscomex, NomePais) values ('847','UZBEQUISTAO, REPUBLICA DO');
insert into Pais (CodigoSiscomex, NomePais) values ('848','VATICANO, EST.DA CIDADE DO');
insert into Pais (CodigoSiscomex, NomePais) values ('850','VENEZUELA');
insert into Pais (CodigoSiscomex, NomePais) values ('858','VIETNA');
insert into Pais (CodigoSiscomex, NomePais) values ('863','VIRGENS,ILHAS (BRITANICAS)');
insert into Pais (CodigoSiscomex, NomePais) values ('866','VIRGENS,ILHAS (E.U.A.)');
insert into Pais (CodigoSiscomex, NomePais) values ('870','FIJI');
insert into Pais (CodigoSiscomex, NomePais) values ('873','WAKE, ILHA');
insert into Pais (CodigoSiscomex, NomePais) values ('875','WALLIS E FUTUNA, ILHAS');
insert into Pais (CodigoSiscomex, NomePais) values ('888','CONGO, REPUBLICA DEMOCRATICA DO');
insert into Pais (CodigoSiscomex, NomePais) values ('890','ZAMBIA');
insert into Pais (CodigoSiscomex, NomePais) values ('895','ZONA DO CANAL DO PANAMA');
insert into Pais (CodigoSiscomex, NomePais) values ('990','PROVISAO DE NAVIOS E AERONAVES');
insert into Pais (CodigoSiscomex, NomePais) values ('994','A DESIGNAR');
insert into Pais (CodigoSiscomex, NomePais) values ('995','BANCOS CENTRAIS');
insert into Pais (CodigoSiscomex, NomePais) values ('997','ORGANIZACOES INTERNACIONAIS');
insert into Pais (CodigoSiscomex, NomePais) values ('998','Delegação Especial da Pales-tina');
