 -- CFOPS
DELETE FROM Cfops
DBCC CHECKIDENT('Cfops', RESEED, 0);
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1101', N'Compra para industrialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1102', N'Compra para comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1111', N'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1113', N'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1116', N'Compra para industrialização originada de encomenda para recebimento futuro')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1117', N'Compra para comercialização originada de encomenda para recebimento futuro')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1118', N'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1120', N'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1121', N'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1122', N'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1124', N'Industrialização efetuada por outra empresa')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1125', N'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1126', N'Compra para utilização na prestação de serviço')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1151', N'Transferência para industrialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1152', N'Transferência para comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1153', N'Transferência de energia elétrica para distribuição')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1154', N'Transferência para utilização na prestação de serviço')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1201', N'Devolução de venda de produção do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1202', N'Devolução de venda de mercadoria adquirida ou recebida de terceiros')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1203', N'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1204', N'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1205', N'Anulação de valor relativo à prestação de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1206', N'Anulação de valor relativo à prestação de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1207', N'Anulação de valor relativo à venda de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1208', N'Devolução de produção do estabelecimento, remetida em transferência')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1209', N'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1251', N'Compra de energia elétrica para distribuição ou comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1252', N'Compra de energia elétrica por estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1253', N'Compra de energia elétrica por estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1254', N'Compra de energia elétrica por estabelecimento prestador de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1255', N'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1256', N'Compra de energia elétrica por estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1257', N'Compra de energia elétrica para consumo por demanda contratada')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1301', N'Aquisição de serviço de comunicação para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1302', N'Aquisição de serviço de comunicação por estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1303', N'Aquisição de serviço de comunicação por estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1304', N'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1305', N'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1306', N'Aquisição de serviço de comunicação por estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1351', N'Aquisição de serviço de transporte para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1352', N'Aquisição de serviço de transporte por estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1353', N'Aquisição de serviço de transporte por estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1354', N'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1355', N'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1356', N'Aquisição de serviço de transporte por estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1401', N'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1403', N'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1406', N'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1407', N'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1408', N'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1409', N'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1410', N'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1411', N'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1414', N'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1415', N'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1451', N'Retorno de animal do estabelecimento produtor')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1452', N'Retorno de insumo não utilizado na produção')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1501', N'Entrada de mercadoria recebida com fim específico de exportação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1503', N'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1504', N'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1551', N'Compra de bem para o ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1552', N'Transferência de bem do ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1553', N'Devolução de venda de bem do ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1554', N'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1555', N'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1556', N'Compra de material para uso ou consumo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1557', N'Transferência de material para uso ou consumo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1601', N'Recebimento, por transferência, de crédito de ICMS')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1602', N'Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1603', N'Ressarcimento de ICMS retido por substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1604', N'Lançamento do crédito relativo à compra de bem para o ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1901', N'Entrada para industrialização por encomenda')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1902', N'Retorno de mercadoria remetida para industrialização por encomenda')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1903', N'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1904', N'Retorno de remessa para venda fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1905', N'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1906', N'Retorno de mercadoria remetida para depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1907', N'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1908', N'Entrada de bem por conta de contrato de comodato')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1909', N'Retorno de bem remetido por conta de contrato de comodato')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1910', N'Entrada de bonificação, doação ou brinde')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1911', N'Entrada de amostra grátis')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1912', N'Entrada de mercadoria ou bem recebido para demonstração')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1913', N'Retorno de mercadoria ou bem remetido para demonstração')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1914', N'Retorno de mercadoria ou bem remetido para exposição ou feira')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1915', N'Entrada de mercadoria ou bem recebido para conserto ou reparo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1916', N'Retorno de mercadoria ou bem remetido para conserto ou reparo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1917', N'Entrada de mercadoria recebida em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1918', N'Devolução de mercadoria remetida em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1919', N'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1920', N'Entrada de vasilhame ou sacaria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1921', N'Retorno de vasilhame ou sacaria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1922', N'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1923', N'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1924', N'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1925', N'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1926', N'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'1949', N'Outra entrada de mercadoria ou prestação de serviço não especificada')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2101', N'Compra para industrialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2102', N'Compra para comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2111', N'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2113', N'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2116', N'Compra para industrialização originada de encomenda para recebimento futuro')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2117', N'Compra para comercialização originada de encomenda para recebimento futuro')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2118', N'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2120', N'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2121', N'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2122', N'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2124', N'Industrialização efetuada por outra empresa')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2125', N'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2126', N'Compra para utilização na prestação de serviço')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2151', N'Transferência para industrialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2152', N'Transferência para comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2153', N'Transferência de energia elétrica para distribuição')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2154', N'Transferência para utilização na prestação de serviço')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2201', N'Devolução de venda de produção do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2202', N'Devolução de venda de mercadoria adquirida ou recebida de terceiros')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2203', N'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2204', N'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2205', N'Anulação de valor relativo à prestação de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2206', N'Anulação de valor relativo à prestação de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2207', N'Anulação de valor relativo à venda de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2208', N'Devolução de produção do estabelecimento, remetida em transferência')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2209', N'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2251', N'Compra de energia elétrica para distribuição ou comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2252', N'Compra de energia elétrica por estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2253', N'Compra de energia elétrica por estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2254', N'Compra de energia elétrica por estabelecimento prestador de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2255', N'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2256', N'Compra de energia elétrica por estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2257', N'Compra de energia elétrica para consumo por demanda contratada')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2301', N'Aquisição de serviço de comunicação para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2302', N'Aquisição de serviço de comunicação por estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2303', N'Aquisição de serviço de comunicação por estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2304', N'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2305', N'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2306', N'Aquisição de serviço de comunicação por estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2351', N'Aquisição de serviço de transporte para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2352', N'Aquisição de serviço de transporte por estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2353', N'Aquisição de serviço de transporte por estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2354', N'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2355', N'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2356', N'Aquisição de serviço de transporte por estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2401', N'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2403', N'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2406', N'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2407', N'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2408', N'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2409', N'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2410', N'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2411', N'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2414', N'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2415', N'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2501', N'Entrada de mercadoria recebida com fim específico de exportação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2503', N'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2504', N'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2551', N'Compra de bem para o ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2552', N'Transferência de bem do ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2553', N'Devolução de venda de bem do ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2554', N'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2555', N'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2556', N'Compra de material para uso ou consumo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2557', N'Transferência de material para uso ou consumo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2603', N'Ressarcimento de ICMS retido por substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2901', N'Entrada para industrialização por encomenda')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2902', N'Retorno de mercadoria remetida para industrialização por encomenda')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2903', N'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2904', N'Retorno de remessa para venda fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2905', N'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2906', N'Retorno de mercadoria remetida para depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2907', N'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2908', N'Entrada de bem por conta de contrato de comodato')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2909', N'Retorno de bem remetido por conta de contrato de comodato')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2910', N'Entrada de bonificação, doação ou brinde')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2911', N'Entrada de amostra grátis')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2912', N'Entrada de mercadoria ou bem recebido para demonstração')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2913', N'Retorno de mercadoria ou bem remetido para demonstração')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2914', N'Retorno de mercadoria ou bem remetido para exposição ou feira')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2915', N'Entrada de mercadoria ou bem recebido para conserto ou reparo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2916', N'Retorno de mercadoria ou bem remetido para conserto ou reparo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2917', N'Entrada de mercadoria recebida em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2918', N'Devolução de mercadoria remetida em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2919', N'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2920', N'Entrada de vasilhame ou sacaria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2921', N'Retorno de vasilhame ou sacaria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2922', N'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2923', N'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2924', N'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2925', N'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'2949', N'Outra entrada de mercadoria ou prestação de serviço não especificado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3101', N'Compra para industrialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3102', N'Compra para comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3126', N'Compra para utilização na prestação de serviço')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3127', N'Compra para industrialização sob o regime de drawback')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3201', N'Devolução de venda de produção do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3202', N'Devolução de venda de mercadoria adquirida ou recebida de terceiros')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3205', N'Anulação de valor relativo à prestação de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3206', N'Anulação de valor relativo à prestação de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3207', N'Anulação de valor relativo à venda de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3211', N'Devolução de venda de produção do estabelecimento sob o regime de drawback')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3251', N'Compra de energia elétrica para distribuição ou comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3301', N'Aquisição de serviço de comunicação para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3351', N'Aquisição de serviço de transporte para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3352', N'Aquisição de serviço de transporte por estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3353', N'Aquisição de serviço de transporte por estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3354', N'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3355', N'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3356', N'Aquisição de serviço de transporte por estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3503', N'Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3551', N'Compra de bem para o ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3553', N'Devolução de venda de bem do ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3556', N'Compra de material para uso ou consumo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3930', N'Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'3949', N'Outra entrada de mercadoria ou prestação de serviço não especificado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5101', N'Venda de produção do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5102', N'Venda de mercadoria adquirida ou recebida de terceiros')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5103', N'Venda de produção do estabelecimento, efetuada fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5104', N'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5105', N'Venda de produção do estabelecimento que não deva por ele transitar')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5106', N'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5109', N'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5110', N'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5111', N'Venda de produção do estabelecimento remetida anteriormente em consignação industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5112', N'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5113', N'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5114', N'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5115', N'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5116', N'Venda de produção do estabelecimento originada de encomenda para entrega futura')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5117', N'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5118', N'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5119', N'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5120', N'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5122', N'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5123', N'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5124', N'Industrialização efetuada para outra empresa')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5125', N'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5151', N'Transferência de produção do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5152', N'Transferência de mercadoria adquirida ou recebida de terceiros')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5153', N'Transferência de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5155', N'Transferência de produção do estabelecimento, que não deva por ele transitar')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5156', N'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5201', N'Devolução de compra para industrialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5202', N'Devolução de compra para comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5205', N'Anulação de valor relativo a aquisição de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5206', N'Anulação de valor relativo a aquisição de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5207', N'Anulação de valor relativo à compra de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5208', N'Devolução de mercadoria recebida em transferência para industrialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5209', N'Devolução de mercadoria recebida em transferência para comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5210', N'Devolução de compra para utilização na prestação de serviço')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5251', N'Venda de energia elétrica para distribuição ou comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5252', N'Venda de energia elétrica para estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5253', N'Venda de energia elétrica para estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5254', N'Venda de energia elétrica para estabelecimento prestador de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5255', N'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5256', N'Venda de energia elétrica para estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5257', N'Venda de energia elétrica para consumo por demanda contratada')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5258', N'Venda de energia elétrica a não contribuinte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5301', N'Prestação de serviço de comunicação para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5302', N'Prestação de serviço de comunicação a estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5303', N'Prestação de serviço de comunicação a estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5304', N'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5305', N'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5306', N'Prestação de serviço de comunicação a estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5307', N'Prestação de serviço de comunicação a não contribuinte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5351', N'Prestação de serviço de transporte para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5352', N'Prestação de serviço de transporte a estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5353', N'Prestação de serviço de transporte a estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5354', N'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5355', N'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5356', N'Prestação de serviço de transporte a estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5357', N'Prestação de serviço de transporte a não contribuinte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5401', N'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5402', N'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5403', N'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituto')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5405', N'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituído')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5408', N'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5409', N'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5410', N'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5411', N'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5412', N'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5413', N'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária.')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5414', N'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5415', N'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5451', N'Remessa de animal e de insumo para estabelecimento produtor')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5501', N'Remessa de produção do estabelecimento, com fim específico de exportação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5502', N'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5503', N'Devolução de mercadoria recebida com fim específico de exportação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5551', N'Venda de bem do ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5552', N'Transferência de bem do ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5553', N'Devolução de compra de bem para o ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5554', N'Remessa de bem do ativo imobilizado para uso fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5555', N'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5556', N'Devolução de compra de material de uso ou consumo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5557', N'Transferência de material de uso ou consumo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5601', N'Transferência de crédito de ICMS acumulado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5602', N'Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5603', N'Ressarcimento de ICMS retido por substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5901', N'Remessa para industrialização por encomenda')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5902', N'Retorno de mercadoria utilizada na industrialização por encomenda')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5903', N'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5904', N'Remessa para venda fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5905', N'Remessa para depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5906', N'Retorno de mercadoria depositada em depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5907', N'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5908', N'Remessa de bem por conta de contrato de comodato')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5909', N'Retorno de bem recebido por conta de contrato de comodato')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5910', N'Remessa em bonificação, doação ou brinde')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5911', N'Remessa de amostra grátis')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5912', N'Remessa de mercadoria ou bem para demonstração')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5913', N'Retorno de mercadoria ou bem recebido para demonstração')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5914', N'Remessa de mercadoria ou bem para exposição ou feira')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5915', N'Remessa de mercadoria ou bem para conserto ou reparo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5916', N'Retorno de mercadoria ou bem recebido para conserto ou reparo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5917', N'Remessa de mercadoria em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5918', N'Devolução de mercadoria recebida em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5919', N'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5920', N'Remessa de vasilhame ou sacaria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5921', N'Devolução de vasilhame ou sacaria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5922', N'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5923', N'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5924', N'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5925', N'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5926', N'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5927', N'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5928', N'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5929', N'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5932', N'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5949', N'Outra saída de mercadoria ou prestação de serviço não especificado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6101', N'Venda de produção do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6102', N'Venda de mercadoria adquirida ou recebida de terceiros')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6103', N'Venda de produção do estabelecimento, efetuada fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6104', N'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6105', N'Venda de produção do estabelecimento que não deva por ele transitar')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6106', N'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6107', N'Venda de produção do estabelecimento, destinada a não contribuinte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6108', N'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6109', N'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6110', N'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6111', N'Venda de produção do estabelecimento remetida anteriormente em consignação industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6112', N'Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6113', N'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6114', N'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6115', N'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6116', N'Venda de produção do estabelecimento originada de encomenda para entrega futura')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6117', N'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6118', N'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6119', N'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6120', N'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6122', N'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6123', N'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6124', N'Industrialização efetuada para outra empresa')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6125', N'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6151', N'Transferência de produção do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6152', N'Transferência de mercadoria adquirida ou recebida de terceiros')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6153', N'Transferência de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6155', N'Transferência de produção do estabelecimento, que não deva por ele transitar')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6156', N'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6201', N'Devolução de compra para industrialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6202', N'Devolução de compra para comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6205', N'Anulação de valor relativo a aquisição de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6206', N'Anulação de valor relativo a aquisição de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6207', N'Anulação de valor relativo à compra de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6208', N'Devolução de mercadoria recebida em transferência para industrialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6209', N'Devolução de mercadoria recebida em transferência para comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6210', N'Devolução de compra para utilização na prestação de serviço')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6251', N'Venda de energia elétrica para distribuição ou comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6252', N'Venda de energia elétrica para estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6253', N'Venda de energia elétrica para estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6254', N'Venda de energia elétrica para estabelecimento prestador de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6255', N'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6256', N'Venda de energia elétrica para estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6257', N'Venda de energia elétrica para consumo por demanda contratada')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6258', N'Venda de energia elétrica a não contribuinte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6301', N'Prestação de serviço de comunicação para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6302', N'Prestação de serviço de comunicação a estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6303', N'Prestação de serviço de comunicação a estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6304', N'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6305', N'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6306', N'Prestação de serviço de comunicação a estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6307', N'Prestação de serviço de comunicação a não contribuinte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6351', N'Prestação de serviço de transporte para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6352', N'Prestação de serviço de transporte a estabelecimento industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6353', N'Prestação de serviço de transporte a estabelecimento comercial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6354', N'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6355', N'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6356', N'Prestação de serviço de transporte a estabelecimento de produtor rural')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6357', N'Prestação de serviço de transporte a não contribuinte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6401', N'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6402', N'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6403', N'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6404', N'Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6408', N'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6409', N'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6410', N'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6411', N'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6412', N'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6413', N'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6414', N'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6415', N'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6501', N'Remessa de produção do estabelecimento, com fim específico de exportação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6502', N'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6503', N'Devolução de mercadoria recebida com fim específico de exportação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6551', N'Venda de bem do ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6552', N'Transferência de bem do ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6553', N'Devolução de compra de bem para o ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6554', N'Remessa de bem do ativo imobilizado para uso fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6555', N'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6556', N'Devolução de compra de material de uso ou consumo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6557', N'Transferência de material de uso ou consumo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6603', N'Ressarcimento de ICMS retido por substituição tributária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6901', N'Remessa para industrialização por encomenda')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6902', N'Retorno de mercadoria utilizada na industrialização por encomenda')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6903', N'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6904', N'Remessa para venda fora do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6905', N'Remessa para depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6906', N'Retorno de mercadoria depositada em depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6907', N'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6908', N'Remessa de bem por conta de contrato de comodato')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6909', N'Retorno de bem recebido por conta de contrato de comodato')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6910', N'Remessa em bonificação, doação ou brinde')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6911', N'Remessa de amostra grátis')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6912', N'Remessa de mercadoria ou bem para demonstração')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6913', N'Retorno de mercadoria ou bem recebido para demonstração')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6914', N'Remessa de mercadoria ou bem para exposição ou feira')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6915', N'Remessa de mercadoria ou bem para conserto ou reparo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6916', N'Retorno de mercadoria ou bem recebido para conserto ou reparo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6917', N'Remessa de mercadoria em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6918', N'Devolução de mercadoria recebida em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6919', N'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6920', N'Remessa de vasilhame ou sacaria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6921', N'Devolução de vasilhame ou sacaria')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6922', N'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6923', N'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6924', N'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6925', N'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6929', N'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6932', N'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6949', N'Outra saída de mercadoria ou prestação de serviço não especificado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7101', N'Venda de produção do estabelecimento')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7102', N'Venda de mercadoria adquirida ou recebida de terceiros')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7105', N'Venda de produção do estabelecimento, que não deva por ele transitar')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7106', N'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7127', N'Venda de produção do estabelecimento sob o regime de drawback')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7201', N'Devolução de compra para industrialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7202', N'Devolução de compra para comercialização')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7205', N'Anulação de valor relativo à aquisição de serviço de comunicação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7206', N'Anulação de valor relativo a aquisição de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7207', N'Anulação de valor relativo à compra de energia elétrica')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7210', N'Devolução de compra para utilização na prestação de serviço')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7211', N'Devolução de compras para industrialização sob o regime de drawback')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7251', N'Venda de energia elétrica para o exterior')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7301', N'Prestação de serviço de comunicação para execução de serviço da mesma natureza')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7358', N'Prestação de serviço de transporte')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7501', N'Exportação de mercadorias recebidas com fim específico de exportação')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7551', N'Venda de bem do ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7553', N'Devolução de compra de bem para o ativo imobilizado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7556', N'Devolução de compra de material de uso ou consumo')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7930', N'Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'7949', N'Outra saída de mercadoria ou prestação de serviço não especificado')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'5931', N'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço')
INSERT Cfops(CodigoCfop, DescricaoCfop) VALUES (N'6931', N'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço')