DBCC CHECKIDENT ('RegrasFiscais', RESEED, 0)
GO
DELETE FROM RegrasFiscais
GO
INSERT RegrasFiscais (CodigoRegraFiscal, DescricaoRegraFiscal, TipoNatureza, TipoDevolucao, MovimentaEstoque, BaseLegal)
  VALUES (N'00001', N'Compra de material para uso e consumo. ICMS 7%, PIS, COFINS, IPI 0%', 0, 2, CONVERT(BIT, 'True'), N'Conf. LC 123/2003')
INSERT RegrasFiscais (CodigoRegraFiscal, DescricaoRegraFiscal, TipoNatureza, TipoDevolucao, MovimentaEstoque, BaseLegal)
  VALUES (N'00002', N'Compra para ind. ICMS 12%, IPI 5%', 0, 2, CONVERT(BIT, 'True'), N'')
INSERT RegrasFiscais (CodigoRegraFiscal, DescricaoRegraFiscal, TipoNatureza, TipoDevolucao, MovimentaEstoque, BaseLegal)
  VALUES (N'00003', N'Venda ICMS 7%, PIS, COFINS', 1, 2, CONVERT(BIT, 'True'), N'')
INSERT RegrasFiscais (CodigoRegraFiscal, DescricaoRegraFiscal, TipoNatureza, TipoDevolucao, MovimentaEstoque, BaseLegal)
  VALUES (N'00004', N'Entrada de serviços - Aliquota 5%', 0, 2, CONVERT(BIT, 'False'), N'')
INSERT RegrasFiscais (CodigoRegraFiscal, DescricaoRegraFiscal, TipoNatureza, TipoDevolucao, MovimentaEstoque, BaseLegal)
  VALUES (N'00005', N'Compra uso e consumo ICMS ñ tributado', 0, 2, CONVERT(BIT, 'True'), N'')
INSERT RegrasFiscais (CodigoRegraFiscal, DescricaoRegraFiscal, TipoNatureza, TipoDevolucao, MovimentaEstoque, BaseLegal)
  VALUES (N'00006', N'Venda c/ IPI tributado 5%, ICMS 12%. PIS, COFINS', 1, 2, CONVERT(BIT, 'True'), N'')
INSERT RegrasFiscais (CodigoRegraFiscal, DescricaoRegraFiscal, TipoNatureza, TipoDevolucao, MovimentaEstoque, BaseLegal)
  VALUES (N'00007', N'Retorno de remessa p/ conserto', 0, 2, CONVERT(BIT, 'False'), N'')
INSERT RegrasFiscais (CodigoRegraFiscal, DescricaoRegraFiscal, TipoNatureza, TipoDevolucao, MovimentaEstoque, BaseLegal)
  VALUES (N'00008', N'Envio de remessa p/ conserto', 1, 2, CONVERT(BIT, 'False'), N'')
INSERT RegrasFiscais (CodigoRegraFiscal, DescricaoRegraFiscal, TipoNatureza, TipoDevolucao, MovimentaEstoque, BaseLegal)
  VALUES (N'00009', N'Compra de bem para o ativo imobilizado ICMS 0%', 0, 2, CONVERT(BIT, 'True'), N'')

GO
DBCC CHECKIDENT ('ImpostosRegraFiscal', RESEED, 0)
GO
DELETE FROM ImpostosRegraFiscal
GO
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (1, 1, 82, 0.00, 6, 5, 3, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (1, 3, 67, 1.65, 0, 0, 3, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (1, 4, 30, 7.60, 0, 0, 3, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (1, 2, 376, 7.00, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (2, 2, 366, 12.00, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (2, 1, 75, 5.00, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (3, 2, 366, 7.00, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (3, 3, 38, 1.65, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (3, 4, 1, 7.60, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (4, 6, 465, 5.00, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (5, 2, 371, 0.00, 1, 0, 2, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (6, 1, 82, 5.00, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (6, 2, 366, 12.00, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (6, 3, 38, 1.65, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (6, 4, 1, 7.60, 0, 0, 1, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (7, 2, 376, 0.00, 6, 0, 3, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (8, 2, 376, 0.00, 6, 0, 3, 0)
INSERT ImpostosRegraFiscal (IdRegraFiscal, IdImposto, IdCst, Aliquota, TipoTributacaoICMS, TipoTributacaoIPI, TipoLancImposto, OperacaoTributariaICMS)
  VALUES (9, 2, 376, 0.00, 1, 0, 3, 0)