DROP LOGIN its
GO 

CREATE LOGIN its WITH PASSWORD = 'its1234'
GO

DROP USER its
GO

CREATE USER its FROM LOGIN its;
GO
GRANT CREATE DATABASE, CREATE TABLE, SELECT, UPDATE, INSERT, DELETE to its WITH GRANT OPTION;
