--http://codigofonte.uol.com.br/codigos/split-no-sql-server
CREATE PROCEDURE dbo.P_SPLIT
AS 
 
    SET NOCOUNT ON
     
    DECLARE @ARRAY VARCHAR(8000), @DELIMITADOR VARCHAR(100), @S VARCHAR(8000)
     
    --teste
    SELECT @ARRAY = 'QUEBREI , A, STRING, POG?'
    --delimitador 
    SELECT @DELIMITADOR = ','
     
    IF LEN(@ARRAY) > 0 SET @ARRAY = @ARRAY + @DELIMITADOR 
    CREATE TABLE #ARRAY(ITEM_ARRAY VARCHAR(8000))
     
    WHILE LEN(@ARRAY) > 0
    BEGIN
       SELECT @S = LTRIM(SUBSTRING(@ARRAY, 1, CHARINDEX(@DELIMITADOR, @ARRAY) - 1))
       INSERT INTO #ARRAY (ITEM_ARRAY) VALUES (@S)
       SELECT @ARRAY = SUBSTRING(@ARRAY, CHARINDEX(@DELIMITADOR, @ARRAY) + 1, LEN(@ARRAY))
    END
     
    -- MOSTRANDO O RESULTADO JÁ POPULADO NA TABELA TEMPORÁRIA
    SELECT * FROM #ARRAY
    DROP TABLE #ARRAY
     
    SET NOCOUNT OFF
GO